<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>async+await异步代码优化</title>
</head>
<body>

<!--<script>
    var b = 20;
    async function fn(){
        let a = 10;
        let myName = await fn22('loading'); // await 后面必须是一个返回 promise 的函数 fn2
        console.log(myName);
    }
    // 普通函数
    function fn22(name) {
        setTimeout(()=>{
            console.log('name:',name)
            return name;
        },2000);
    }

    // fn2 必须是一个 Promise
    function fn2(name){
        return new Promise((resolve,reject) => {
                    setTimeout(() => {
                        resolve(name);
                    },1000)
                })
    }

    fn() //undefined
</script>-->

<!-- 将上述代码修改成以下就正常了 -->
<script>
    var b = 20;
    async function fn(){
        let a = 10;
        let myName = await fn2('cooking'); //  await 是要等待 promise的. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
        console.log(myName);
    }
    function fn2(name) {
        return new Promise(resolve => {
            setTimeout(() => {
            resolve(name);
            }, 2000);
        });
    }
    fn() // cooking
</script>

<!-- //async修饰的函数总是返回一个Promise对象，是为了用异步的方式实现同步逻辑。
//If a Promise is passed to an await expression, 
//it waits for the Promise to be fulfilled and returns the fulfilled value. -->

<!--<script>
var b = 20;
    async function fn(){
        let a = 10;
        let myName = '初始值';
        myName = await fn2('loading');
        console.log(myName);
    }

    //这样会先输出111,再输入loading，如果不使用async，由于setTimeout是异步的，会先输出undefind再输出111
    async function fn2(name) {  
        return new Promise(resolve => {
            setTimeout(() => {
              console.log(111)
              resolve(name);
            }, 2000);
          });
    }
    fn()
</script>-->
<!-- 特定时间后打印1 -->
<!--<script>
    var b = 20;
    async function fn(val,ms){
        let a = 10;
        await fn2(ms);
        console.log(val);   
    }
    function fn2(ms) {
        /*return new Promise((resolve)=>{
            setTimeout(resolve,ms)
        })*/
        return new Promise((resolve,reject)=>{
                    setTimeout(() => {
                        resolve()
                    },ms)
                })
    }
    fn('loading',3000) // loading
</script>-->
<!--特定时间后打印2-->
<!--<script>

    async function gen(){
        let p1 = await print('1');
        let p2 = await print('2');
        let p3 = await print('3');
    };

    function print(val){
        return new Promise(function (resolve, reject){
            setTimeout(()=>{
                console.log(val);
                resolve(val);
            },1000);
        });
    };

    gen() // 1...2...3
</script>-->

<!--<script>
//经过async修饰之后，自动变成promise对象
async function f() {
  return 'hello world';
}

f().then(v => console.log(v))  // "hello world" ,去掉 async后会报错
</script>-->

<!--<script>
//错误处理
async function f() {
  throw new Error('出错了');
}

f().then(
  v => console.log(v),
  e => console.log(e)
)
// Error: 出错了
</script>-->
</body>
</html>